import { PageType } from "../../../Types/PageType";

export const PageOne: PageType = {
   data: [
      {
         id: 1,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 2,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 3,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 4,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 5,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 6,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 7,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 8,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 9,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 10,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
   ],
   pageNumber: 1,
   totalCount: 19,
   totalPages: 2,
};

export const PageTwo: PageType = {
   data: [
      {
         id: 11,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 12,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 13,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 14,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 15,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 16,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 17,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 18,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
      {
         id: 19,
         authorName: "Abdolah",
         authorId: 233,
         subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
         status: "open",
         replies: [],
         createdAt: "19/09/2012",
      },
   ],
   pageNumber: 2,
   totalCount: 19,
   totalPages: 2,
};
