export const CarouselDummyData = [
   {
      id: 110,
      name: "Tulip",
      price: 1,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/tulips-flowers.jpg.avif",
      discount: 5,
      category: "flower",
   },
   {
      id: 111,
      name: "Orchid",
      price: 2,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/orchids-flowers.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 112,
      name: "Sunflower",
      price: 3,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/sunflower-flower.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 113,
      name: "Lily",
      price: 3.5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lilies-flowers.jpg.avif",
      discount: 3,
      category: "flower",
   },
   {
      id: 114,
      name: "Daffodil",
      price: 2.5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/daffodils-flowers1.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 115,
      name: "Marigold",
      price: 1.5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/marigold-flowers1.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 116,
      name: "Lotus",
      price: 7,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lotus-flowers.jpg.avif",
      discount: 20,
      category: "flower",
   },
   {
      id: 117,
      name: "Dahlia",
      price: 3,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/dahlia-flowers.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 118,
      name: "Gladioli",
      price: 4,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/gladiolus-flowers.jpg.avif",
      discount: 0,
      category: "flower",
   },
   {
      id: 119,
      name: "Carnation",
      price: 5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/carnations-flowers.jpg.avif",
      discount: 0,
      category: "flower",
   },
];
