export const ProfileDummyData = {
   notifications: [
      {
         subject: "qwerty1",
         message: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         read: false,
         id: 124,
         sentDate: "1999/01/01",
         readDate: "",
      },
      {
         subject: "qwerty2",
         message: "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
         read: true,
         id: 123,
         sentDate: "1999/01/01",
         readDate: "2000/01/01",
      },
   ],
   tickets: [
      {
         subject: "qwerty3",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "Not perused",
      },
      {
         subject: "qwerty4",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "open",
      },
      {
         subject: "qwerty5",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "closed",
      },
   ],
   orders: [
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2007/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 30,
         totalItems: 20,
         discount: 100,
         purchaseDate: "2008/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2009/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2010/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
   ],
   wishList: [
      {
         name: "qwerty",
         price: "123",
         available: true,
         image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
         id: 123,
      },
      {
         name: "qwerty",
         price: "321",
         available: false,
         image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
         id: 213,
      },
   ],
   mileStones: [
      {
         stage: 1,
         requiredScore: 1000,
         prize: {
            id: 123,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
      {
         stage: 2,
         requiredScore: 2000,
         prize: {
            id: 1233,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
      {
         stage: 3,
         requiredScore: 3000,
         prize: {
            id: 1234,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
   ],
   giftCards: [
      {
         minimalPurchase: 123,
         maximalPurchase: 124,
         dicount: 10,
         used: false,
         code: "3Davinci-siktir1",
         subject: "The third anniversary of 3DAVINCI group",
         beginningDate: "1987/01/01",
         expirationDate: "1998/01/01",
      },
      {
         minimalPurchase: 100,
         maximalPurchase: 200,
         dicount: 20,
         used: true,
         code: "3Davinci-siktir2",
         subject: "The fourth anniversary of 3DAVINCI group",
         beginningDate: "2003/01/01",
         expirationDate: "2003/01/02",
      },
   ],
};

export const NewProfileDummyData = {
   notifications: [
      {
         subject: "qwerty1",
         message: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         read: true,
         id: 124,
         sentDate: "1999/01/01",
         readDate: "2001/01/01",
      },
      {
         subject: "qwerty2",
         message: "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",
         read: true,
         id: 123,
         sentDate: "1999/01/01",
         readDate: "2000/01/01",
      },
   ],
   tickets: [
      {
         subject: "qwerty3",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "Not perused",
      },
      {
         subject: "qwerty4",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "open",
      },
      {
         subject: "qwerty5",
         text: "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
         status: "closed",
      },
   ],
   orders: [
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2007/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 30,
         totalItems: 20,
         discount: 100,
         purchaseDate: "2008/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2009/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
      {
         id: 123456,
         totalPrice: 400,
         totalItems: 10,
         discount: 100,
         purchaseDate: "2010/01/01",
         status: "Sent",
         items: [
            {
               count: 3,
               product: {
                  id: 123,
                  name: "qwer",
                  price: "123",
                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
                  discount: "10",
                  category: "George",
                  selectedColor: "#E8320E",
                  selectedSize: "sm",
               },
            },
         ],
      },
   ],
   wishList: [
      {
         name: "qwerty",
         price: "123",
         available: true,
         image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
         id: 123,
      },
      {
         name: "qwerty",
         price: "321",
         available: false,
         image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
         id: 213,
      },
   ],
   mileStones: [
      {
         stage: 1,
         requiredScore: 1000,
         prize: {
            id: 123,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
      {
         stage: 2,
         requiredScore: 2000,
         prize: {
            id: 1233,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
      {
         stage: 3,
         requiredScore: 3000,
         prize: {
            id: 1234,
            name: "qwer",
            price: "123",
            image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROHxYft1f_Ln_y_scKnh8-g5rLMmce7JKyPQ&s",
            discount: "10",
            category: "George",
            selectedColor: "#E8320E",
            selectedSize: "sm",
         },
      },
   ],
   giftCards: [
      {
         minimalPurchase: 123,
         maximalPurchase: 124,
         dicount: 10,
         used: true,
         code: "3Davinci-siktir1",
         subject: "The third anniversary of 3DAVINCI group",
         beginningDate: "1987/01/01",
         expirationDate: "1998/01/01",
      },
      {
         minimalPurchase: 100,
         maximalPurchase: 200,
         dicount: 20,
         used: true,
         code: "3Davinci-siktir2",
         subject: "The fourth anniversary of 3DAVINCI group",
         beginningDate: "2003/01/01",
         expirationDate: "2003/01/02",
      },
   ],
};
