import { PageType } from "../../Types/PageType.tsx";

export const ShopPageOne: PageType = {
   data: [
      {
         id: 110,
         name: "Rose",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/rose-flower.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 111,
         name: "Tulip",
         price: 1,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/tulips-flowers.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 112,
         name: "Orchid",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/orchids-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 113,
         name: "Sunflower",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/sunflower-flower.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 114,
         name: "Lily",
         price: 3.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lilies-flowers.jpg.avif",
         discount: 3,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 115,
         name: "Daffodil",
         price: 2.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/daffodils-flowers1.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 116,
         name: "Marigold",
         price: 1.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/marigold-flowers1.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 117,
         name: "Lotus",
         price: 7,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lotus-flowers.jpg.avif",
         discount: 20,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 118,
         name: "Dahlia",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/dahlia-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 119,
         name: "Gladioli",
         price: 4,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/gladiolus-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
   ],
   pageNumber: 1,
   totalPages: 5,
   totalCount: 50,
};

export const ShopPageTwo: PageType = {
   data: [
      {
         id: 120,
         name: "Carnations",
         price: 1,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/carnations-flowers.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 121,
         name: "Chrysanthemums",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/chrysanthemums-flower.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 122,
         name: "Apple blossom",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/apple-blossom-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 123,
         name: "Camellia",
         price: 3.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/camellia-flowers.jpg.avif",
         discount: 3,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 124,
         name: "Iris",
         price: 2.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/iris-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 125,
         name: "Lilac",
         price: 1.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lilac-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 126,
         name: "Peony",
         price: 7,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/peony-flowers.jpg.avif",
         discount: 20,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 127,
         name: "Sweet pea",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/sweet-pea-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 128,
         name: "Magnolia",
         price: 4,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/magnolia-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 129,
         name: "Lavender",
         price: 5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lavender-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
   ],
   pageNumber: 2,
   totalPages: 5,
   totalCount: 50,
};

export const ShopPageThree: PageType = {
   data: [
      {
         id: 130,
         name: "Ranunculus",
         price: 1,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/ranunculus-flowers.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 131,
         name: "Stock",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/stock-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 132,
         name: "Statice",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/statice-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 133,
         name: "Proteas",
         price: 3.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/proteas-flowers.jpg.avif",
         discount: 3,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 134,
         name: "Queen Anne’s Lace",
         price: 2.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/queen-anne-lace-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 135,
         name: "Poinsettia",
         price: 1.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/poinsettia-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 136,
         name: "Snapdragons",
         price: 7,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/snapdragons-flowers.jpg.avif",
         discount: 20,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 137,
         name: "Lisianthus",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lisianthus-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 138,
         name: "Freesia",
         price: 4,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/freesia-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 139,
         name: "Delphinium",
         price: 5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/delphinium-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
   ],
   pageNumber: 3,
   totalPages: 5,
   totalCount: 50,
};

export const ShopPageFour: PageType = {
   data: [
      {
         id: 140,
         name: "Bourvardia",
         price: 1,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/bourvardia-flowers.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 141,
         name: "Daisies",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/daisies-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 142,
         name: "Hydrangea",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/hydrangea-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 143,
         name: "Aster",
         price: 3.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/aster-flowers.jpg.avif",
         discount: 3,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 144,
         name: "Bird Of Paradise",
         price: 2.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/bird-of-paradise-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 145,
         name: "Heather",
         price: 1.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/heather-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 146,
         name: "Anthurium",
         price: 7,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/anthurium-flowers.jpg.avif",
         discount: 20,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 147,
         name: "Anemone",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/anemone-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 148,
         name: "Crocus",
         price: 4,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/crocus-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 149,
         name: "Amaryllis",
         price: 5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/amaryllis-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
   ],
   pageNumber: 4,
   totalPages: 5,
   totalCount: 50,
};

export const ShopPageFive: PageType = {
   data: [
      {
         id: 150,
         name: "Alstromeria",
         price: 1,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/alstroemeria-flowers.jpg.avif",
         discount: 5,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 151,
         name: "Pansy",
         price: 2,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/pansy-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 152,
         name: "Cherry Blossom",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/cherry-blossom-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 153,
         name: "Cypress",
         price: 3.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/cypress-flowers.jpg.avif",
         discount: 3,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 154,
         name: "Hibiscus",
         price: 2.5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/hibiscus-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 155,
         name: "Jasmine",
         price: 1.5,
         image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmjnfGFbreMI44LkRDqTCc9Os1d44X2eEf7Q&s",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 156,
         name: "Morning Glory",
         price: 7,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/morning-glory-flowers.jpg.avif",
         discount: 20,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 157,
         name: "Violet",
         price: 3,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/violet-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 158,
         name: "Gerberas",
         price: 4,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/gerberas-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
      {
         id: 159,
         name: "Laurel",
         price: 5,
         image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/laurel-flowers.jpg.avif",
         discount: 0,
         category: "flower",
         selectedColor: "#4287f5",
         selectedSize: "md",
         colors: ["#67d4db", "#5ede50", "#eb154e"],
         sizes: ["sm", "lg"],
         score: {
            totalScore: 3.5,
            quality: 4,
            conformity: 3,
            intact: 4,
            economical: 3,
         },
         sales: 200,
         description:
            "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque, ea soluta. Laborum, consequuntur eos temporibus dolorem alias ex quis totam doloribus corporis consectetur perspiciatis, placeat quae consequatur minima quam voluptatem.",
      },
   ],
   pageNumber: 5,
   totalPages: 5,
   totalCount: 50,
};
