import { ProductSchemeType } from "../../Types/ProductType";
export const SpecialOffersDummyData: ProductSchemeType[] = [
   {
      id: 110,
      name: "Tulip",
      price: 1,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/tulips-flowers.jpg.avif",
      discount: 5,
      category: "flower",
      selectedColor: "#4287f5",
      selectedSize: "sm",
      colors: ["#67d4db", "#5ede50", "#eb154e"],
      sizes: ["sm", "lg"],
      score: {
         totalScore: 3.5,
         quality: 4,
         conformity: 3,
         intact: 4,
         economical: 3,
      },
      sales: 100,
   },
   {
      id: 116,
      name: "Lotus",
      price: 7,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lotus-flowers.jpg.avif",
      discount: 20,
      category: "flower",
      selectedColor: "#4287f5",
      selectedSize: "sm",
      colors: ["#67d4db", "#5ede50", "#eb154e"],
      sizes: ["sm", "lg"],
      score: {
         totalScore: 3.5,
         quality: 4,
         conformity: 3,
         intact: 4,
         economical: 3,
      },
      sales: 100,
   },
   {
      id: 113,
      name: "Lily",
      price: 3.5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/lilies-flowers.jpg.avif",
      discount: 3,
      category: "flower",
      selectedColor: "#4287f5",
      selectedSize: "sm",
      colors: ["#67d4db", "#5ede50", "#eb154e"],
      sizes: ["sm", "lg"],
      score: {
         totalScore: 3.5,
         quality: 4,
         conformity: 3,
         intact: 4,
         economical: 3,
      },
      sales: 100,
   },
   {
      id: 119,
      name: "Carnation",
      price: 5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/carnations-flowers.jpg.avif",
      discount: 10,
      category: "flower",
      selectedColor: "#4287f5",
      selectedSize: "md",
      colors: ["#67d4db", "#5ede50", "#eb154e"],
      sizes: ["sm", "lg"],
      score: {
         totalScore: 3.5,
         quality: 4,
         conformity: 3,
         intact: 4,
         economical: 3,
      },
      sales: 200,
   },
   {
      id: 144,
      name: "Bird Of Paradise",
      price: 2.5,
      image: "https://cdn2.stylecraze.com/wp-content/uploads/2013/07/bird-of-paradise-flowers.jpg.avif",
      discount: 15,
      category: "flower",
      selectedColor: "#4287f5",
      selectedSize: "md",
      colors: ["#67d4db", "#5ede50", "#eb154e"],
      sizes: ["sm", "lg"],
      score: {
         totalScore: 3.5,
         quality: 4,
         conformity: 3,
         intact: 4,
         economical: 3,
      },
      sales: 200,
   },
];
