import { OrderType } from "../../Types/OrderType";

export const ProccessingOrders: OrderType[] = [
   {
      id: 123,
      totalPrice: 244,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "processing",
      customerName: "Agha Javad",
      customerId: 456,
      shippedDate: "unknown",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 3,
            product: {
               id: 66,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
   {
      id: 125,
      totalPrice: 244,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha Jalal",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
   {
      id: 120,
      totalPrice: 244,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha Reza",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
   {
      id: 1233,
      totalPrice: 244,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha Reza",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
   {
      id: 124,
      totalPrice: 244,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha Reza",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
];

export const ShippedOrders: OrderType[] = [
   {
      id: 989,
      totalPrice: 13,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha qwerty",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
   {
      id: 984,
      totalPrice: 13,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha asdfgh",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 24,
               name: "dfgh",
               price: 122,
               image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
];

export const DeliveredOrders: OrderType[] = [
   {
      id: 456,
      totalPrice: 67,
      totalItems: 20,
      discount: 0,
      purchaseDate: "19/02/2020",
      status: "shipped",
      customerName: "Agha pioutyui",
      customerId: 456,
      shippedDate: "20/02/2020",
      deliveredDate: "unknown",
      items: [
         {
            count: 2,
            product: {
               id: 23,
               name: "qwerty",
               price: 122,
               image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
         {
            count: 2,
            product: {
               id: 25,
               name: "rtyu",
               price: 122,
               image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
               discount: 0,
               category: "sh",
               selectedColor: "#4287f5",
               selectedSize: "sm",
               score: {
                  totalScore: 4,
                  conformity: 4,
                  economical: 4,
                  intact: 4,
                  quality: 4,
               },
               sales: 258,
            },
         },
      ],
   },
];
