import { TicketType } from "../../Types/TicketType";

export const SingleTicket: TicketType = {
   id: 1,
   authorName: "Abdolah",
   authorId: 233,
   subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
   text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
   status: "closed",
   createdAt: "19/09/2012",
   replies: [
      {
         id: 12345,
         ticketId: 1,
         authorName: "3DavinciGroup",
         authorId: 999999,
         receiverName: "Abdolah",
         receiverId: 233,
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo",
         createdAt: "19/09/2012",
      },
      {
         id: 12346,
         ticketId: 1,
         authorName: "Abdolah",
         authorId: 233,
         receiverName: "3DavinciGroup",
         receiverId: 999999,
         text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam,",
         createdAt: "19/09/2012",
      },
      {
         id: 12347,
         ticketId: 1,
         authorName: "3DavinciGroup",
         authorId: 999999,
         receiverName: "Abdolah",
         receiverId: 233,
         text: "Lorem ipsum dolor",
         createdAt: "19/09/2012",
      },
   ],
};

export const OpenTickets: TicketType[] = [
   {
      id: 1,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "open",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 2,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "open",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 3,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "open",
      replies: [],
      createdAt: "19/09/2012",
   },
];

export const ClosedTickets: TicketType[] = [
   {
      id: 4,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "closed",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 5,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "closed",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 6,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "closed",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 7,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "closed",
      replies: [],
      createdAt: "19/09/2012",
   },
];

export const InProgressTickets: TicketType[] = [
   {
      id: 8,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "in-progress",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 9,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "in-progress",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 10,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "in-progress",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 11,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "in-progress",
      replies: [],
      createdAt: "19/09/2012",
   },
   {
      id: 12,
      authorName: "Abdolah",
      authorId: 233,
      subject: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo, reprehenderit ab delectus minus aperiam, sequi fugit ipsa magni odio veritatis quibusdam minima, unde repudiandae! Quam sapiente consequatur ad quo excepturi.",
      status: "in-progress",
      replies: [],
      createdAt: "19/09/2012",
   },
];
