import { PageType } from "../../../Types/PageType";

export const PageOne: PageType = {
   data: [
      {
         id: 1,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 3,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 4,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 5,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 6,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 7,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 8,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 9,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 10,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 1,
   totalCount: 24,
   totalPages: 3,
};
export const PageTwo: PageType = {
   data: [
      {
         id: 11,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 12,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 13,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 14,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 15,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 16,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 17,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 18,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 19,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 20,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 2,
   totalCount: 24,
   totalPages: 3,
};
export const PageThree: PageType = {
   data: [
      {
         id: 21,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 22,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 23,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 24,
         image: "https://www.photo.gallery/render/w1024-c2.1/blog/image-size-quality-photo-gallery-websites/image-size-quality-photo-gallery-websites.jpg",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 3,
   totalCount: 24,
   totalPages: 3,
};
