import { PageType } from "../../../Types/PageType";

export const PageOne: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 3,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 4,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 5,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 6,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 7,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 8,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 9,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 10,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 1,
   totalCount: 72,
   totalPages: 8,
};
export const PageTwo: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 2,
   totalCount: 72,
   totalPages: 8,
};
export const PageThree: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 3,
   totalCount: 72,
   totalPages: 8,
};
export const PageFour: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 4,
   totalCount: 72,
   totalPages: 8,
};
export const PageFive: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 5,
   totalCount: 72,
   totalPages: 8,
};
export const PageSix: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 6,
   totalCount: 72,
   totalPages: 8,
};
export const PageSeven: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 7,
   totalCount: 72,
   totalPages: 8,
};
export const PageEight: PageType = {
   data: [
      {
         id: 1,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
      {
         id: 2,
         image: "https://storage.googleapis.com/gweb-uniblog-publish-prod/images/watermarked_photo_squirrel_snow.max-768x768.format-webp.webp",
         description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Porro nobis blanditiis, ducimus laboriosam accusantium iste maxime, ab ipsam harum voluptatibus ullam vitae sapiente, quos provident aut molestiae. Similique, voluptatibus maiores.",
         customerId: 202,
         customerName: "Asad",
         status: "processing",
         orderedDate: "05/12/2003",
         shippedDate: "Unknown",
         deliveredDate: "Unknown",
      },
   ],
   pageNumber: 8,
   totalCount: 72,
   totalPages: 8,
};
