import { PageType } from "../../../Types/PageType";

export const PageOne: PageType = {
   data: [
      {
         id: 1,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 2,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 3,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 4,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 5,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 6,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 7,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 8,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 9,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 10,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
   ],
   pageNumber: 1,
   totalCount: 28,
   totalPages: 3,
};

export const PageTwo: PageType = {
   data: [
      {
         id: 11,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 12,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 13,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 14,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 15,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 16,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 17,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 18,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 19,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 20,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
   ],
   pageNumber: 2,
   totalCount: 28,
   totalPages: 3,
};
export const PageThree: PageType = {
   data: [
      {
         id: 21,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 22,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 23,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 24,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 25,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 26,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 27,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
      {
         id: 28,
         totalPrice: 244,
         totalItems: 20,
         discount: 0,
         purchaseDate: "19/02/2020",
         status: "processing",
         customerName: "Agha Javad",
         customerId: 456,
         shippedDate: "unknown",
         deliveredDate: "unknown",
         items: [
            {
               count: 2,
               product: {
                  id: 23,
                  name: "qwerty",
                  price: 122,
                  image: "https://www.industrialempathy.com/img/remote/ZiClJf-1920w.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 25,
                  name: "rtyu",
                  price: 122,
                  image: "https://cdn.pixabay.com/photo/2024/05/26/10/15/bird-8788491_1280.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 2,
               product: {
                  id: 24,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
            {
               count: 3,
               product: {
                  id: 66,
                  name: "dfgh",
                  price: 122,
                  image: "https://gratisography.com/wp-content/uploads/2024/11/gratisography-augmented-reality-800x525.jpg",
                  discount: 0,
                  category: "sh",
                  selectedColor: "#4287f5",
                  selectedSize: "sm",
                  score: {
                     totalScore: 4,
                     conformity: 4,
                     economical: 4,
                     intact: 4,
                     quality: 4,
                  },
                  sales: 258,
               },
            },
         ],
      },
   ],
   pageNumber: 3,
   totalCount: 28,
   totalPages: 3,
};
